In [97]:
import pandas as pd

In [98]:
df1=pd.read_excel('data/1.xlsx')

In [99]:
import numpy as  np

In [27]:
ant_left_hip_x = df1['l_hip_x'] - df1['l_knee_x']

In [26]:
ant_left_hip_y = df1['l_hip_y'] - df1['l_knee_y']

In [20]:
ant_aa_l = df1['l_ankle_x'] - df1['l_knee_x'],df1['l_ankle_y'] - df1['l_knee_y']

In [202]:
pd_ant = pd.DataFrame({'left_kh_x':df1['l_hip_x'] - df1['l_knee_x'], 
                       'left_kh_y':df1['l_hip_y'] - df1['l_knee_y'],
                       'left_ka_x':df1['l_knee_x'] - df1['l_ankle_x'],
                       'left_ka_y':df1['l_knee_y'] - df1['l_ankle_y']})

In [212]:
pd_ant['l_tibia_x'] = df1['l_knee_x'] - df1['l_ankle_x']
pd_ant['l_tibia_y'] = df1['l_knee_y'] - df1['l_ankle_y']
pd_ant['l_femur_x'] = df1['l_hip_x'] - df1['l_knee_x']
pd_ant['l_femur_y'] = df1['l_hip_y'] - df1['l_knee_y']

In [213]:
pd_ant[0:10]

,left_kh_x,left_kh_y,left_ka_x,left_ka_y,l_tibia_x,l_tibia_y,l_femur_x,l_femur_y
0,-39.57220,366.5385,-40.79694,322.5818,-40.79694,322.5818,-39.57220,366.5385
1,-42.17360,364.2803,-39.51360,313.0984,-39.51360,313.0984,-42.17360,364.2803
2,-42.17360,364.2803,-39.51360,313.0984,-39.51360,313.0984,-42.17360,364.2803
3,-42.17360,364.2803,-39.51360,313.0984,-39.51360,313.0984,-42.17360,364.2803
4,-44.30096,360.5879,-5.85570,352.4101,-5.85570,352.4101,-44.30096,360.5879
5,-44.30096,360.5879,-5.85570,352.4101,-5.85570,352.4101,-44.30096,360.5879
6,-44.30096,360.5879,-5.85570,352.4101,-5.85570,352.4101,-44.30096,360.5879
7,-49.83800,356.4099,-5.85560,352.4107,-5.85560,352.4107,-49.83800,356.4099
8,-49.83800,356.4099,-5.85560,352.4107,-5.85560,352.4107,-49.83800,356.4099
9,-49.83800,356.4099,-5.85560,352.4107,-5.85560,352.4107,-49.83800,356.4099

In [230]:
angle_v2(pd_ant[['l_tibia_x','l_tibia_y']].values,       pd_ant[['l_femur_x','l_femur_y']].values     )[0:10]

array([-1.04603804, -0.58893883, -0.58893883, -0.58893883,  6.05217421,
        6.05217421,  6.05217421,  7.00831698,  7.00831698,  7.00831698])

In [226]:
pd_ant[['l_tibia_x','l_tibia_y']]

     l_tibia_x  l_tibia_y
0    -40.79694   322.5818
1    -39.51360   313.0984
2    -39.51360   313.0984
3    -39.51360   313.0984
4     -5.85570   352.4101
..         ...        ...
442  -41.88466   322.1639
443  -41.88466   322.1639
444  -41.75889   321.9552
445  -41.75889   321.9552
446  -41.75889   321.9552

[447 rows x 2 columns]

In [196]:
np_v1 = pd_ant[['left_kh_x','left_kh_y']]

In [197]:
np_v2 = pd_ant[['left_ka_x','left_ka_y']]

In [228]:
def angle_v2(vec1, vec2):
    #import math
    import numpy as np

    np.array 
    
    # 각 벡터의 각도 계산 (x축 기준)
    angle1 = np.arctan2(vec1[:,1], vec1[:,0])
    angle2 = np.arctan2(vec2[:,1], vec2[:,0])

    # 두 각도의 차이 계산
    angle_diff_rad = angle2 - angle1

    # 절대값 및 360도 조정 (필요에 따라)
    angle_diff_deg = np.degrees(angle_diff_rad)
    #angle_diff_deg = np.where( angle_diff_deg < 0, angle_diff_deg + 360, angle_diff_deg )

    return angle_diff_deg

In [205]:
angle_v2(v1, v2)[1:10]

array([-3.13131373, -3.13131373, -3.13131373, -3.24722302, -3.24722302,
       -3.24722302, -3.26391086, -3.26391086, -3.26391086])

In [206]:
a1= np.arctan2(v2[:,1], v2[:,0]) - np.arctan2(v1[:,1], v1[:,0])

In [207]:
np.where(a1<0, a1+360, a1)[1:10]

array([356.86868627, 356.86868627, 356.86868627, 356.75277698,
       356.75277698, 356.75277698, 356.73608914, 356.73608914,
       356.73608914])

In [162]:
np.where(a1<0,'a1<0','a1>=0')

array('a1<0', dtype='<U5')

In [156]:
np.arctan2(v2[:,1], v2[:,0])[4]

np.float64(-1.55418170316054)

In [100]:
v1 = np.array(pd_ant[['left_kh_x','left_kh_y']])

In [101]:
v2 = np.array(pd_ant[['left_ka_x','left_ka_y']])

In [231]:
180-np.degrees(np.arccos( (v1*v2).sum(axis=1) / ( np.linalg.norm(v1, axis=1) * np.linalg.norm(v2, axis=1) ) ) )[0:10]

array([1.04603804, 0.58893883, 0.58893883, 0.58893883, 6.05217421,
       6.05217421, 6.05217421, 7.00831698, 7.00831698, 7.00831698])

In [113]:
import math

In [114]:
math.atan2(v1[1],v1[0])

TypeError: only length-1 arrays can be converted to Python scalars

In [67]:
np.matmul(v1,v2.reshape(2,447))

array([[-114417.52773647,   23723.15988656, -116694.37258587, ...,
        -119344.6169696 ,   27410.4350639 , -119309.87653522],
       [-113828.6904265 ,   24494.81393716, -116087.85654777, ...,
        -118705.38018976,   28111.84148519, -118668.35598632],
       [-113828.6904265 ,   24494.81393716, -116087.85654777, ...,
        -118705.38018976,   28111.84148519, -118668.35598632],
       ...,
       [-117261.86972398,   23926.65343418, -119597.89163402, ...,
        -122322.26575008,   27727.74971809, -122287.72593341],
       [-117261.86972398,   23926.65343418, -119597.89163402, ...,
        -122322.26575008,   27727.74971809, -122287.72593341],
       [-117261.86972398,   23926.65343418, -119597.89163402, ...,
        -122322.26575008,   27727.74971809, -122287.72593341]],
      shape=(447, 447))

In [75]:
np.dot(v1, v2[:,None])

ValueError: shapes (447,2) and (447,1,2) not aligned: 2 (dim 1) != 1 (dim 1)

In [128]:
# A is the 2D array, shape (M, N)
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [7, 8, 9]
])
B = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
C= np.array([1.2])
# v is the 1D vector, shape (N,)
v = np.array([1, 0, 2])

# Reshape v to a column vector (N, 1) using np.newaxis or None
v_col = v[:, np.newaxis]
# or v_col = v[:, None]

# The result of the matrix multiplication will broadcast across the rows of A
# The resulting shape is (M, 1), a column vector of dot products

In [94]:
(A*B).sum(axis=1)

array([ 14,  32, 122, 194])

In [82]:
A.shape

(3, 3)

In [86]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
v_col.shape

(3, 1)

In [85]:
np.dot(A,B)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [232]:
#Low back arch

df1

,timestamp,head_x,head_y,head_z,torso_x,torso_y,torso_z,waist_x,waist_y,waist_z,...,r_hip_z,r_knee_x,r_knee_y,r_knee_z,l_ankle_x,l_ankle_y,l_ankle_z,r_ankle_x,r_ankle_y,r_ankle_z
0,1743993607,-66.57459,346.6133,2153.312,-53.08918,-76.51717,2227.077,-42.61894,-253.0159,2199.219,...,2200.213,-146.0421,-645.2217,2094.135,139.9366,-954.6445,2234.752,-180.1308,-968.9515,2229.294
1,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
2,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
3,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
4,1743993608,-45.28284,330.4109,2149.211,-51.05178,-87.53446,2226.210,-43.04076,-265.1855,2202.331,...,2200.013,-151.5682,-664.8762,2056.333,110.5179,-1002.7690,2058.162,-180.9913,-975.9042,2219.510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,1743993622,-71.18983,360.3356,2118.724,-50.02530,-57.78058,2173.144,-44.92595,-239.8437,2154.254,...,2160.997,-161.4635,-664.4786,2077.935,135.1745,-976.7439,2232.596,-175.5972,-990.8358,2226.992
443,1743993622,-71.18983,360.3356,2118.724,-50.02530,-57.78058,2173.144,-44.92595,-239.8437,2154.254,...,2160.997,-161.4635,-664.4786,2077.935,135.1745,-976.7439,2232.596,-175.5972,-990.8358,2226.992
444,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622
445,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622
446,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622

In [233]:
lat_pd = df1[['torso_y', 'torso_z', 'waist_y','waist_z','l_hip_y','l_hip_z','l_knee_y','l_knee_z','l_ankle_y','l_ankle_z']]

In [234]:
lat_pd['tor_wai_y'] = lat_pd['torso_y'] - lat_pd['waist_y']
lat_pd['tor_wai_z'] = lat_pd['torso_z'] - lat_pd['waist_z']
lat_pd['l_hip_wai_y'] = lat_pd['waist_y'] - lat_pd['l_hip_y']
lat_pd['l_hip_wai_z'] = lat_pd['waist_z'] - lat_pd['l_hip_z']
lat_pd['l_tibia_y'] = lat_pd['l_knee_y'] - lat_pd['l_ankle_y']
lat_pd['l_tibia_z'] = lat_pd['l_knee_z'] - lat_pd['l_ankle_z']

C:\Users\김선우\AppData\Local\Temp\ipykernel_29184\356035953.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_pd['tor_wai_y'] = lat_pd['torso_y'] - lat_pd['waist_y']
C:\Users\김선우\AppData\Local\Temp\ipykernel_29184\356035953.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_pd['tor_wai_z'] = lat_pd['torso_z'] - lat_pd['waist_z']
C:\Users\김선우\AppData\Local\Temp\ipykernel_29184\356035953.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_pd['l_hip_wai_y'] = lat_pd['waist_y'] - lat_pd['l_hip_y']
C:\Users\김선우\AppData\Local\Temp\ipykernel_29184\356035953.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_pd['l_hip_wai_z'] = lat_pd['waist_z'] - lat_pd['l_hip_z']
C:\Users\김선우\AppData\Local\Temp\ipykernel_29184\356035953.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_pd['l_tibia_y'] = lat_pd['l_knee_y'] - lat_pd['l_ankle_y']
C:\Users\김선우\AppData\Local\Temp\ipykernel_29184\356035953.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lat_pd['l_tibia_z'] = lat_pd['l_knee_z'] - lat_pd['l_ankle_z']

In [242]:
pd_lat = pd.DataFrame()

In [243]:
pd_lat['tor_wai_y'] = lat_pd['torso_y'] - lat_pd['waist_y']
pd_lat['tor_wai_z'] = lat_pd['torso_z'] - lat_pd['waist_z']
pd_lat['l_hip_wai_y'] = lat_pd['waist_y'] - lat_pd['l_hip_y']
pd_lat['l_hip_wai_z'] = lat_pd['waist_z'] - lat_pd['l_hip_z']
pd_lat['l_tibia_y'] = lat_pd['l_knee_y'] - lat_pd['l_ankle_y']
pd_lat['l_tibia_z'] = lat_pd['l_knee_z'] - lat_pd['l_ankle_z']

In [244]:
pd_lat

     tor_wai_y  tor_wai_z  l_hip_wai_y  l_hip_wai_z  l_tibia_y  l_tibia_z
0    176.49873     27.858      12.5083       -8.714   322.5818   -136.042
1    177.91545     23.093      26.1839       -5.629   313.0984   -156.968
2    177.91545     23.093      26.1839       -5.629   313.0984   -156.968
3    177.91545     23.093      26.1839       -5.629   313.0984   -156.968
4    177.65104     23.879      24.5855       -5.593   352.4101      1.899
..         ...        ...          ...          ...        ...        ...
442  182.06312     18.890      41.3296      -11.325   322.1639   -152.915
443  182.06312     18.890      41.3296      -11.325   322.1639   -152.915
444  183.06743     18.680      45.2912      -11.938   321.9552   -147.741
445  183.06743     18.680      45.2912      -11.938   321.9552   -147.741
446  183.06743     18.680      45.2912      -11.938   321.9552   -147.741

[447 rows x 6 columns]

In [251]:
angle_v2(pd_lat[['tor_wai_y', 'tor_wai_z']].values, pd_lat[['l_hip_wai_y','l_hip_wai_z']].values)[1:10]

array([-19.52826228, -19.52826228, -19.52826228, -20.47174008,
       -20.47174008, -20.47174008, -23.73355201, -23.73355201,
       -23.73355201])

In [254]:
angle_v2(pd_lat[['tor_wai_y', 'tor_wai_z']].values, pd_lat[['l_tibia_y','l_tibia_z']].values)

array([-31.8359379 , -34.02183777, -34.02183777, -34.02183777,
        -7.34679683,  -7.34679683,  -7.34679683,  -8.39086991,
        -8.39086991,  -8.39086991,  -8.39086991, -39.14362165,
       -39.85861378, -42.28125645, -44.03910633, -45.81277677,
       -47.1871012 , -48.74229991, -49.11906927, -49.11906927,
       -49.11906927, -49.11906927, -46.83035541, -46.83035541,
       -46.83035541, -43.27326755, -43.27326755, -43.27326755,
       -42.39249222, -42.39249222, -43.77418098, -43.77418098,
       -43.77418098, -44.22042762, -44.22042762, -44.22042762,
       -44.62393332, -44.62393332, -44.62393332, -43.88401119,
       -43.88401119, -41.89189449, -41.84691539, -41.4524965 ,
       -40.05328272, -38.95191127, -38.36155005, -38.12047115,
       -38.12047115, -38.12047115, -38.3280776 , -38.3280776 ,
       -38.3280776 , -39.00368171, -39.00368171, -39.00368171,
       -37.17787891, -37.17787891, -37.17787891, -37.42534863,
       -37.42534863, -37.42534863, -37.42534863, -37.57295551,
       -37.57295551, -37.57295551, -36.56585065, -36.56585065,
       -36.31812527, -36.31812527, -36.31812527, -37.27096604,
       -37.03545113, -36.27050436, -34.58098333, -34.68744851,
       -35.20283142, -35.38520684, -35.38520684, -35.38520684,
       -34.21091777, -34.21091777, -34.21091777, -32.87384139,
       -32.87384139, -32.87384139, -29.78473639, -29.78473639,
       -29.78473639, -29.78473639, -27.11489424, -27.11489424,
       -27.11489424, -26.10453241, -26.10453241, -25.81190828,
       -25.81190828, -25.81190828, -27.88960002, -27.88960002,
       -27.88960002, -28.41941031, -25.98737134, -23.12632435,
       -22.28586208, -22.07861087, -21.23237675, -21.23237675,
       -21.23237675, -21.23237675, -19.770484  , -19.770484  ,
       -19.770484  , -19.36723687, -19.36723687, -19.79469898,
       -19.79469898, -19.79469898, -19.79469898, -21.71814724,
       -21.71814724, -21.71814724, -21.90424549, -21.90424549,
       -24.44182368, -24.44182368, -24.44182368, -24.44182368,
       -29.26165443, -29.26165443, -29.26165443, -32.25326109,
       -34.91465012, -36.57245113, -37.64864386, -38.30758236,
       -37.86324116, -38.94175734, -38.94175734, -38.94175734,
       -38.81142679, -38.81142679, -38.81142679, -41.21935361,
       -41.21935361, -41.21935361, -42.51717596, -42.51717596,
       -42.51717596, -41.95573349, -41.95573349, -39.91616283,
       -39.91616283, -39.91616283, -39.26955915, -39.26955915,
       -39.26955915, -33.54654671, -33.54654671, -33.54654671,
       -36.51057912, -36.51057912, -39.52656373, -41.0096155 ,
       -39.97503631, -38.9030854 , -36.91063349, -34.33882806,
       -31.39750339, -31.39750339, -31.39750339, -31.39750339,
       -28.86659698, -28.86659698, -28.86659698, -28.86659698,
       -28.1543118 , -28.1543118 , -28.1543118 , -28.1543118 ,
       -25.29661761, -25.29661761, -25.29661761, -22.84068565,
       -22.84068565, -22.84068565, -22.85513381, -22.85513381,
       -22.85513381, -24.01566133, -24.80281632, -24.98702381,
       -24.46607374, -24.24788557, -24.34067526, -24.45508372,
       -24.45508372, -24.45508372, -24.76644269, -24.76644269,
       -24.76644269, -25.10165765, -25.10165765, -25.10165765,
       -25.10165765, -25.79275477, -25.79275477, -25.79275477,
       -25.91636135, -25.91636135, -25.91636135, -27.44262896,
       -27.44262896, -29.82622407, -29.82622407, -29.82622407,
       -33.81070161, -33.81070161, -33.81070161, -39.27704635,
       -39.27704635, -39.27704635, -39.84977525, -38.43855834,
       -38.33372368, -41.5517686 , -43.31834809, -43.70227917,
       -43.70227917, -43.70227917, -42.65751328, -42.65751328,
       -42.65751328, -44.26595907, -44.26595907, -44.26595907,
       -38.24870254, -38.24870254, -38.24870254, -22.93356547,
       -22.93356547, -22.93356547, -20.47038522, -20.47038522,
       -20.47038522, -26.40968666, -26.40968666, -23.80438486,
       -23.80438486, -23.80438486, -24.47680082, -24.47680082,
       -22.48203435, -24.91153814, -44.34345172, -36.05264975,
       -38.85696555, -36.38730185, -34.50850531, -34.50850531,
       -34.50850531, -34.31678504, -34.31678504, -34.31678504,
       -34.31678504, -34.43602212, -34.43602212, -30.83413334,
       -30.83413334, -30.83413334, -27.48783215, -27.48783215,
       -27.48783215, -27.48783215, -26.21350876, -26.21350876,
       -24.76416411, -24.76416411, -24.76416411, -23.43261948,
       -23.43261948, -23.2299699 , -22.84851281, -22.48524516,
       -21.95325407, -22.50628107, -24.00833188, -26.04968641,
       -26.04968641, -26.04968641, -24.52325184, -24.52325184,
       -24.52325184, -22.99078184, -22.99078184, -22.99078184,
       -21.62668626, -21.62668626, -21.62668626, -22.35421941,
       -22.35421941, -27.8757343 , -27.8757343 , -27.8757343 ,
       -33.02958728, -33.02958728, -33.02958728, -33.08479397,
       -33.08479397, -32.22896703, -32.22896703, -32.22896703,
       -33.99937538, -34.90326277, -37.30380575, -40.5368318 ,
       -42.32614747, -42.94678785, -27.79600376, -27.79600376,
       -27.79600376, -28.67676633, -28.67676633, -28.67676633,
       -28.67676633, -27.02388355, -27.02388355, -27.02388355,
       -25.10854856, -25.10854856, -16.96333304, -16.96333304,
       -16.96333304, -16.14400449, -16.14400449, -16.14400449,
       -15.50800931, -15.50800931, -15.50800931, -16.49452884,
       -16.49452884, -19.76470559, -47.88251918, -41.81058162,
       -38.58919166, -37.75335047, -35.83510558, -33.64970661,
       -33.64970661, -33.64970661, -31.04229022, -31.04229022,
       -31.04229022, -29.06349782, -29.06349782, -29.06349782,
       -28.64505256, -28.64505256, -28.02799597, -28.02799597,
       -28.02799597, -27.17456581, -27.17456581, -27.17456581,
       -26.68115541, -26.68115541, -26.68115541, -26.67426854,
       -26.67426854, -26.74119265, -26.74119265, -26.74119265,
       -26.4463895 , -25.73581414, -24.84535121, -24.60342599,
       -25.04776024, -25.35392925, -25.59080578, -25.59080578,
       -25.59080578, -25.05303654, -25.05303654, -25.05303654,
       -25.05303654, -25.31023643, -25.31023643, -25.31023643,
       -27.70620525, -27.70620525, -27.70620525, -28.76144204,
       -28.76144204, -28.76144204, -31.53201108, -31.53201108,
       -31.53201108, -33.55843763, -33.55843763, -33.55843763,
       -35.60218274, -38.87905275, -40.49741604, -41.02710897,
       -38.85709085,   0.34588027,   0.3002188 ,   0.74216534,
         0.73351487,   0.73351487,   0.73351487,   0.34467638,
         0.34467638,   0.34467638,   0.22779408,   0.22779408,
         0.22779408,   0.35009238,   0.35009238,   0.35009238,
        -0.84111481,  -0.84111481,  -3.28684117,  -3.28684117,
        -3.28684117,  -2.85164222,  -2.85164222,  -2.85164222,
        -2.36482503,  -2.36482503,  -2.36482503,  -3.05685466,
        -3.8605787 ,  -4.07681292,  -4.43988588, -36.25925064,
       -37.01010814, -35.01713077, -33.34964848, -33.34964848,
       -33.34964848, -31.31488146, -31.31488146, -31.31488146,
       -30.47600035, -30.47600035, -30.47600035])