In [1]:
import pandas as pd

In [2]:
import numpy as np

In [21]:
df1=pd.read_excel('../data/4.xlsx')

In [22]:
df1

,timestamp,head_x,head_y,head_z,torso_x,torso_y,torso_z,waist_x,waist_y,waist_z,...,r_hip_z,r_knee_x,r_knee_y,r_knee_z,l_ankle_x,l_ankle_y,l_ankle_z,r_ankle_x,r_ankle_y,r_ankle_z
0,1745902161,-55.827060,452.776000,2256.349000,-8.589788,-46.445630,2456.054574,-11.476924,-288.092188,2548.472704,...,2610.742919,-158.138462,-808.252767,2647.366011,184.149087,-1239.500686,2662.635675,-216.254749,-1291.341201,2681.851566
1,1745902161,-55.662468,443.680069,2255.534015,-8.880306,-47.249917,2550.045473,-11.288994,-265.974698,2569.248279,...,2626.830046,-160.701638,-831.511317,2536.473171,183.880384,-1241.898209,2504.922929,-221.110197,-1288.180608,2746.310804
2,1745902161,-55.662468,443.680069,2255.534015,-7.982223,-69.252356,2541.725718,-10.974598,-266.384842,2573.346661,...,2729.016387,-156.399549,-820.171016,2558.478415,196.647998,-1179.951554,2801.257686,-220.325607,-1180.001105,2607.530292
3,1745902161,-55.662468,443.680069,2255.534015,-8.300296,-115.668437,2576.150664,-9.836442,-336.098893,2561.674202,...,2626.869004,-154.713555,-840.264884,2582.042984,193.411557,-1168.444279,2841.110996,-223.716550,-1286.802618,2595.407049
4,1745902161,-55.222988,416.846417,2255.213920,-8.135528,-110.783699,2537.074331,-10.337059,-328.342306,2714.477583,...,2689.689621,-158.014725,-831.614317,2514.756104,201.103875,-1165.892635,2717.337183,-211.842938,-1243.741908,2732.845330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1745902171,-42.067361,452.110793,2230.480329,-4.386789,-19.476487,2529.370552,-6.705935,-205.301837,2431.323683,...,2564.342109,-149.897007,-801.130534,2594.501249,186.267584,-1123.438584,2700.560450,-214.141822,-1090.382390,2756.976167
305,1745902171,-42.067361,452.110793,2230.480329,4.190194,4.108042,2459.711514,2.017044,-195.726803,2481.780290,...,2619.171719,-136.099150,-783.234231,2619.954201,180.154902,-1132.372738,2788.677432,-216.677760,-1193.929603,2571.766029
306,1745902171,-42.067361,452.110793,2230.480329,4.320268,8.230436,2514.683065,1.901079,-184.063544,2579.058793,...,2577.358939,-147.063852,-743.307687,2675.657789,191.566231,-1106.596699,2832.879180,-203.823994,-1125.397462,2569.512704
307,1745902171,-41.910100,443.106957,2230.080484,4.151057,8.288149,2364.732426,1.779079,-187.223885,2489.923143,...,2572.415929,-147.037869,-747.263248,2630.630989,175.742054,-1128.854822,2574.219035,-215.869739,-1046.488934,2783.817009
308,1745902171,-41.910100,443.106957,2230.080484,4.408622,8.407602,2585.573547,1.980006,-184.607074,2490.358737,...,2644.489734,-148.483279,-733.696974,2583.514130,188.177295,-1130.693707,2628.737585,-214.688528,-1138.597245,2710.519891

In [23]:
df_ant = df1[['l_hip_x','l_hip_y','l_knee_x','l_knee_y','l_ankle_x','l_ankle_y']]

In [24]:
df_ant

        l_hip_x     l_hip_y    l_knee_x    l_knee_y   l_ankle_x    l_ankle_y
0    107.733394 -361.112112  130.113143 -845.492115  184.149087 -1239.500686
1    112.604582 -350.280776  140.102875 -782.229191  183.880384 -1241.898209
2    110.778499 -376.979206  145.040137 -829.152187  196.647998 -1179.951554
3    108.371615 -400.368206  139.998511 -887.184110  193.411557 -1168.444279
4    109.472398 -386.986860  151.076787 -879.063208  201.103875 -1165.892635
..          ...         ...         ...         ...         ...          ...
304   94.104964 -336.745144  135.177828 -762.599874  186.267584 -1123.438584
305   88.028521 -349.899483  127.370178 -737.610897  180.154902 -1132.372738
306   88.060778 -343.274659  129.263875 -751.073776  191.566231 -1106.596699
307   92.255395 -364.030771  132.946568 -729.269821  175.742054 -1128.854822
308   89.901185 -335.122947  128.533714 -707.319128  188.177295 -1130.693707

[309 rows x 6 columns]

In [25]:
pd.set_option('mode.chained_assignment', None)
df_ant['l_tibia_x'] = df1['l_knee_x'] - df1['l_ankle_x']
df_ant['l_tibia_y'] = df1['l_knee_y'] - df1['l_ankle_y']
df_ant['l_femur_x'] = df1['l_hip_x'] - df1['l_knee_x']
df_ant['l_femur_y'] = df1['l_hip_y'] - df1['l_knee_y']

In [26]:
df_ant

,l_hip_x,l_hip_y,l_knee_x,l_knee_y,l_ankle_x,l_ankle_y,l_tibia_x,l_tibia_y,l_femur_x,l_femur_y
0,107.733394,-361.112112,130.113143,-845.492115,184.149087,-1239.500686,-54.035944,394.008571,-22.379749,484.380003
1,112.604582,-350.280776,140.102875,-782.229191,183.880384,-1241.898209,-43.777509,459.669018,-27.498293,431.948415
2,110.778499,-376.979206,145.040137,-829.152187,196.647998,-1179.951554,-51.607861,350.799367,-34.261638,452.172981
3,108.371615,-400.368206,139.998511,-887.184110,193.411557,-1168.444279,-53.413046,281.260169,-31.626896,486.815904
4,109.472398,-386.986860,151.076787,-879.063208,201.103875,-1165.892635,-50.027088,286.829427,-41.604389,492.076349
...,...,...,...,...,...,...,...,...,...,...
304,94.104964,-336.745144,135.177828,-762.599874,186.267584,-1123.438584,-51.089756,360.838709,-41.072864,425.854730
305,88.028521,-349.899483,127.370178,-737.610897,180.154902,-1132.372738,-52.784724,394.761842,-39.341657,387.711414
306,88.060778,-343.274659,129.263875,-751.073776,191.566231,-1106.596699,-62.302356,355.522922,-41.203097,407.799118
307,92.255395,-364.030771,132.946568,-729.269821,175.742054,-1128.854822,-42.795486,399.585001,-40.691173,365.239050
308,89.901185,-335.122947,128.533714,-707.319128,188.177295,-1130.693707,-59.643581,423.374579,-38.632529,372.196181

In [27]:
def angle_v2(vec1, vec2):
    # from google
    #import math
    import numpy as np

    np.array 
    
    # 각 벡터의 각도 계산 (x축 기준)
    angle1 = np.arctan2(vec1[:,1], vec1[:,0])
    angle2 = np.arctan2(vec2[:,1], vec2[:,0])

    # 두 각도의 차이 계산
    angle_diff_rad = angle2 - angle1

    # 절대값 및 360도 조정 (필요에 따라)
    angle_diff_deg = np.degrees(angle_diff_rad)
    #angle_diff_deg = np.where( angle_diff_deg < 0, angle_diff_deg + 360, angle_diff_deg )

    return angle_diff_deg

In [28]:
angle_v2(df_ant[['l_tibia_x','l_tibia_y']].values,       df_ant[['l_femur_x','l_femur_y']].values     )[0:50]

array([-5.16371287e+00, -1.79767682e+00, -4.03595486e+00, -7.03567651e+00,
       -5.06088187e+00, -4.96644414e+00, -2.54552512e+00,  6.43192002e-02,
       -4.97040854e+00, -3.83691453e+00, -2.75093801e+00,  8.68886148e+00,
        6.18176101e-03,  5.19519696e+00,  8.53532362e+00,  8.77758457e+00,
        7.11458615e+00,  5.44264705e+00,  7.87489029e+00,  1.04661778e+01,
        9.60392323e+00,  8.74941174e+00,  4.79621042e+00,  8.40062998e+00,
        1.37141829e+01,  6.95462724e+00,  1.48615793e+01,  1.22541789e+01,
        1.36836941e+01,  2.03636764e+01,  2.00373819e+01,  1.43410117e+01,
        1.31928436e+01,  1.20110776e+01,  1.16610268e+01,  1.66154916e+01,
        1.39506935e+01,  8.21912736e+00,  1.61088024e+01,  1.25350068e+01,
        7.65036823e+00,  1.12604337e+01,  2.80093750e+00, -4.78035606e+00,
        2.13512120e+00, -2.92023165e-01,  1.43134829e+00,  1.88269034e+00,
       -2.66140912e+00,  8.74666126e-01])

In [29]:
#lateral view
df_lat = df1[['torso_y', 'torso_z', 'waist_y','waist_z','l_hip_y','l_hip_z','l_knee_y','l_knee_z','l_ankle_y','l_ankle_z']]

In [30]:
df_lat['tor_wai_y'] = df_lat['torso_y'] - df_lat['waist_y']
df_lat['tor_wai_z'] = df_lat['torso_z'] - df_lat['waist_z']
df_lat['l_hip_wai_y'] = df_lat['waist_y'] - df_lat['l_hip_y']
df_lat['l_hip_wai_z'] = df_lat['waist_z'] - df_lat['l_hip_z']
df_lat['l_tibia_y'] = df_lat['l_knee_y'] - df_lat['l_ankle_y']
df_lat['l_tibia_z'] = df_lat['l_knee_z'] - df_lat['l_ankle_z']

In [31]:
#low back arch
angle_v2(df_lat[['tor_wai_y', 'tor_wai_z']].values, df_lat[['l_hip_wai_y','l_hip_wai_z']].values)[1:50]

array([ -62.54719542,  -11.06012915,  -80.97269804,    2.62709251,
         14.99326698,  -89.25237872,  -63.3815991 ,   -0.26042614,
        -24.9028247 ,  -73.97101989,   -3.30331933,  -36.56235767,
        -83.02349183, -108.96455313,  -42.89930668,  -51.75024168,
        -47.76977187,  -77.78896534,   51.60819288,  -36.78483847,
        -93.74432768, -110.87082237,  -34.65901758,  -96.923378  ,
        -82.9429951 ,  -84.39785456, -100.17739338,  -93.96623147,
         21.68484753,  -70.69237191,  -79.94370064,  102.44336389,
        -70.68811552,  -12.15477528,  -73.04854937,  -69.64634045,
        -84.03065565,  -22.43059972,  -99.7056252 ,   70.06684111,
       -121.78819129,  147.4716334 ,  -38.17930284,  -68.72112512,
        108.08335653, -128.27184878, -101.1547584 ,  -19.28047803,
         -3.102557  ])

In [32]:
#torso lean forward
angle_v2(df_lat[['l_tibia_y','l_tibia_z']].values, df_lat[['tor_wai_y', 'tor_wai_z']].values)[1:200]

array([-16.61425182,  41.37805958,  42.47734921,  -2.39771811,
        28.29936236,  12.97165889,   4.99077819,   7.99826437,
         5.9248035 ,   4.7922594 ,  43.67191683,  33.79538201,
        39.44835764,  59.59903394,  -4.94808855,   9.61123409,
        15.39250914,  34.66696678,   3.07346017,   4.99689565,
        34.20460139,  75.42272809,   4.31741554,  63.84869939,
        55.15498385,  46.9967544 ,  69.06165237,  69.23633146,
       -12.35568874,  57.79982718,  53.29294538,  26.92408633,
        32.75378033,  30.93503997,  77.27578007,  58.84143748,
        47.90793009,  -1.76164803,  25.56307689,  54.61242861,
        98.4698372 ,   3.84044709,  14.48679905, -25.14231545,
       -24.82710828,  85.04860234,  58.14685863,  11.22724876,
         8.84359693,  -3.75826802,  19.87090678,  59.40943877,
        40.13709268,  49.52415226,  13.11095302, -47.89157874,
        -4.38982727, -36.32823461,  12.34832983, -11.02036269,
       -35.69644183,  34.05809024, -30.34239689,   5.70368297,
        12.66549958, -26.11364104, -25.85862622,  14.56251096,
         7.43355107,  15.71741967,  40.7440679 ,  29.82477819,
        -4.87822181,  24.37843965, -29.22726215,  77.59238754,
        17.78042633, -19.45122804,  63.83321329, -18.01067473,
        36.37009216,  31.64969443,  19.68521799,  68.2255934 ,
        39.39744677,  62.32667032,  29.80113595,  19.15715593,
        54.2733236 ,  19.84087329,  18.27684129,  13.07384986,
        24.54500542,  43.59537316,   9.9063364 ,  82.32086479,
        50.77949337,  14.28627694,  84.27204114,  37.81220284,
        17.74576654,  55.00216957,  44.56369025,  29.87247503,
        48.95067284,  14.67075261, -36.58648503,  69.0451843 ,
        -0.91882042,  11.75425819, -12.15079282,  72.42051276,
        23.81291502,  10.97427209, -26.76941732, -12.14778728,
        47.25551741, -43.96243449,  63.9794165 , -33.58281545,
       -61.38634079,  40.37483836, -22.10287843,  53.06885194,
       -39.26560712,  67.85696898, -27.37976472, -16.33229744,
       -22.94245285, -37.91787626,  -7.02800663,  60.29731261,
       -21.60284583,  -3.22801664,   3.81652947,   6.15830835,
        22.11573736, -27.35221339,  32.3980015 ,  37.17624547,
        43.63356679,   4.41025317,  12.15463479,  -6.50014537,
        56.38826191,  14.66483873,  47.25869665,  51.23459564,
        59.70376702, 112.53044382,  63.27854421,  82.92451279,
        74.7044349 , 113.57084147,  29.45061707,  47.41190439,
        60.80442951,  24.41197811,  83.16512989,  82.11555339,
        19.12469429,  45.29512096,  76.01403313,  23.05448572,
        62.14779625,  86.86670493,  62.77489672,  -3.36157272,
        44.31472006,  12.5130561 , -63.19419651,  -3.86163411,
       -17.81091894,  26.94349769,  71.63656594, -42.23847582,
        11.97108804, -15.62282732,  -5.61306795, -34.93096411,
         9.23945182, -42.17412472,  44.09750595,  52.09719186,
       -21.54727124,  66.55575959, -22.95312629, -19.94567984,
       -16.3412783 , -32.25595873, -39.37777119, -43.29818958,
        -2.83496769,  27.60621334,  40.57378373,  21.61114618,
       -23.31323846, -23.90990462,  33.31527133])

In [33]:
df_lat[0:50]

,torso_y,torso_z,waist_y,waist_z,l_hip_y,l_hip_z,l_knee_y,l_knee_z,l_ankle_y,l_ankle_z,tor_wai_y,tor_wai_z,l_hip_wai_y,l_hip_wai_z,l_tibia_y,l_tibia_z
0,-46.445630,2456.054574,-288.092188,2548.472704,-361.112112,2777.353548,-845.492115,2620.311328,-1239.500686,2662.635675,241.646558,-92.418130,73.019924,-228.880844,394.008571,-42.324347
1,-47.249917,2550.045473,-265.974698,2569.248279,-350.280776,2773.431775,-782.229191,2599.253251,-1241.898209,2504.922929,218.724780,-19.202807,84.306078,-204.183496,459.669018,94.330322
2,-69.252356,2541.725718,-266.384842,2573.346661,-376.979206,2613.978311,-829.152187,2375.841190,-1179.951554,2801.257686,197.132487,-31.620943,110.594364,-40.631650,350.799367,-425.416496
3,-115.668437,2576.150664,-336.098893,2561.674202,-400.368206,2844.906095,-887.184110,2615.618479,-1168.444279,2841.110996,220.430456,14.476462,64.269312,-283.231893,281.260169,-225.492518
4,-110.783699,2537.074331,-328.342306,2714.477583,-386.986860,2757.979525,-879.063208,2502.784563,-1165.892635,2717.337183,217.558607,-177.403251,58.644554,-43.501942,286.829427,-214.552620
5,-111.332508,2591.481082,-311.546950,2555.591107,-395.624221,2516.106114,-865.909685,2583.040121,-1270.220380,2715.475080,200.214442,35.889975,84.077271,39.484993,404.310695,-132.434959
6,-125.237247,2577.205081,-361.130902,2534.174287,-397.843840,2721.550529,-875.341364,2612.705380,-1206.791076,2627.951523,235.893655,43.030794,36.712938,-187.376242,331.449712,-15.246143
7,-130.184873,2560.991061,-348.766443,2552.464018,-425.935407,2692.530127,-837.646446,2626.224192,-1229.444491,2645.089912,218.581570,8.527043,77.168963,-140.066109,391.798046,-18.865720
8,-170.046139,2582.806094,-360.652397,2693.122669,-467.531643,2755.631069,-930.330633,2541.156739,-1202.552547,2754.292351,190.606258,-110.316575,106.879245,-62.508400,272.221914,-213.135612
9,-157.149208,2512.399861,-386.399733,2586.133380,-423.782650,2620.668140,-899.321567,2540.267016,-1234.152366,2687.624539,229.250524,-73.733519,37.382917,-34.534760,334.830799,-147.357524
10,-175.270243,2580.204441,-396.143299,2543.627429,-444.942890,2646.251453,-864.699699,2550.572903,-1326.918240,2513.296815,220.873056,36.577012,48.799591,-102.624024,462.218541,37.276087
11,-208.517055,2733.802053,-399.014449,2682.863314,-510.714083,2659.798022,-862.115868,2451.956268,-1310.309379,2697.348810,190.497394,50.938739,111.699634,23.065293,448.193511,-245.392542
12,-205.030321,2632.792431,-430.880136,2656.666477,-490.870236,2711.823534,-891.191439,2373.183435,-1262.771117,2683.097019,225.849814,-23.874046,59.990100,-55.157057,371.579678,-309.913584
13,-205.220072,2540.860635,-451.083764,2533.147600,-498.431984,2839.942120,-894.866481,2404.350838,-1206.737678,2644.970967,245.863692,7.713034,47.348220,-306.794520,311.871196,-240.620128
14,-272.217086,2514.606495,-469.934832,2413.190653,-521.499369,2771.457583,-948.490895,2428.894179,-1310.497357,2659.023065,197.717747,101.415843,51.564537,-358.266930,362.006462,-230.128886
15,-272.395504,2516.286041,-495.593040,2611.600576,-547.031027,2727.261373,-901.230119,2521.121405,-1271.287642,2642.621164,223.197535,-95.314534,51.437988,-115.660797,370.057524,-121.499758
16,-276.012535,2617.411325,-494.421316,2590.724744,-560.665267,2656.471119,-932.142190,2598.372503,-1294.419380,2615.108544,218.408781,26.686580,66.243951,-65.746374,362.277190,-16.736041
17,-292.634826,2519.988766,-527.560439,2650.446135,-558.157525,2781.038726,-927.732726,2357.713858,-1306.787970,2729.385716,234.925613,-130.457369,30.597086,-130.592591,379.055244,-371.671857
18,-283.266380,2549.258659,-502.449354,2530.488718,-530.999858,2623.260907,-949.794106,2442.345104,-1277.913760,2630.050629,219.182974,18.769941,28.550504,-92.772189,328.119654,-187.705525
19,-330.053711,2666.608728,-538.126949,2734.518229,-611.085017,2686.168058,-885.037909,2587.343974,-1357.273379,2770.026238,208.073238,-67.909501,72.958069,48.350171,472.235470,-182.682264
20,-363.490167,2408.066439,-575.813680,2524.823639,-603.238006,2585.255942,-955.552094,2462.141204,-1264.202746,2668.791286,212.323512,-116.757201,27.424326,-60.432303,308.650653,-206.650082
21,-393.489295,2453.889249,-611.488945,2488.647996,-583.407651,2612.212899,-1039.203635,2375.804963,-1399.112285,2714.536852,217.999650,-34.758748,-28.081294,-123.564903,359.908650,-338.731889
22,-423.001789,2644.519595,-617.393251,2509.508300,-666.316782,2707.044854,-1052.591702,2413.543509,-1333.723700,2654.855972,194.391462,135.011294,48.923532,-197.536554,281.131998,-241.312463
23,-417.793525,2445.264047,-618.639312,2584.879159,-647.234896,2661.213517,-1030.439830,2515.529475,-1256.146152,2699.099748,200.845787,-139.615112,28.595584,-76.334358,225.706323,-183.570273
24,-463.560621,2557.199226,-666.368242,2490.173586,-708.140178,2697.998891,-1028.532416,2552.253918,-1310.383158,2839.674362,202.807621,67.025640,41.771936,-207.825305,281.850742,-287.420444
25,-443.289917,2501.141524,-647.279494,2524.151641,-650.134991,2787.507236,-1097.691995,2517.048055,-1316.813856,2922.149459,203.989577,-23.010117,2.855497,-263.355595,219.121860,-405.101404
26,-451.277332,2571.816840,-674.426403,2571.420884,-690.690944,2734.260970,-1087.215319,2402.143698,-1321.313885,2652.263904,223.149071,0.395956,16.264541,-162.840086,234.098566,-250.120206
27,-478.603089,2416.288344,-674.302841,2348.718148,-704.057303,2539.354987,-1048.467604,2463.971325,-1326.364162,2795.309931,195.699752,67.570196,29.754462,-190.636839,277.896558,-331.338607
28,-497.680356,2500.834804,-724.047092,2498.534676,-710.357957,2730.036548,-1117.858359,2495.382668,-1249.966233,2833.422563,226.366736,2.300128,-13.689135,-231.501872,132.107873,-338.039895
29,-509.113613,2547.827605,-677.336970,2627.641327,-741.313630,2631.775367,-1090.356901,2574.039611,-1298.947548,2622.297626,168.223357,-79.813722,63.976660,-4.134040,208.590646,-48.258014
30,-499.669707,2467.253161,-694.520366,2443.938462,-740.810963,2538.300612,-1115.659217,2434.194680,-1317.209688,2682.880926,194.850659,23.314699,46.290597,-94.362150,201.550472,-248.686246
31,-502.291452,2548.058727,-672.750025,2566.802288,-683.040023,2722.494609,-1119.047645,2349.163411,-1305.722883,2666.936358,170.458573,-18.743561,10.289998,-155.692320,186.675238,-317.772946
32,-470.389457,2511.956362,-683.493622,2585.109781,-689.174325,2535.271941,-1106.009626,2442.990474,-1365.636600,2710.625790,213.104165,-73.153419,5.680703,49.837841,259.626974,-267.635316
33,-466.193108,2440.847625,-659.031719,2513.331582,-654.556173,2712.344033,-1048.155666,2393.461974,-1333.332605,2776.809111,192.838610,-72.483956,-4.475546,-199.012451,285.176939,-383.347138
34,-451.003689,2458.154939,-645.992410,2584.109836,-710.037924,2648.190267,-1100.220004,2364.456493,-1301.512764,2773.463141,194.988720,-125.954897,64.045514,-64.080432,201.292760,-409.006648
35,-477.187311,2530.487254,-650.254746,2473.372595,-704.391568,2550.073629,-1077.264562,2440.485539,-1345.394754,2886.943934,173.067435,57.114658,54.136823,-76.701034,268.130192,-446.458394
36,-440.809480,2575.174414,-647.184963,2554.892083,-680.690536,2623.690465,-1066.838990,2461.675595,-1428.267022,2945.307822,206.375484,20.282332,33.505573,-68.798383,361.428032,-483.632227
37,-440.922653,2496.354326,-665.816700,2565.053417,-637.047064,2712.824064,-1102.350828,2431.570229,-1318.464979,2892.807902,224.894047,-68.699091,-28.769636,-147.770647,216.114151,-461.237673
38,-450.889221,2458.355836,-602.597563,2605.162880,-646.183854,2705.356422,-983.481430,2463.489673,-1384.754572,2828.590723,151.708342,-146.807045,43.586291,-100.193542,401.273142,-365.101050
39,-447.696908,2513.977011,-661.149374,2515.953392,-631.957636,2677.609484,-1003.920803,2538.593686,-1345.021104,2705.649534,213.452466,-1.976380,-29.191738,-161.656093,341.100302,-167.055848
40,-414.149528,2549.883418,-599.641353,2562.879489,-616.855110,2524.109201,-1023.596240,2333.485150,-1284.101962,2760.600241,185.491826,-12.996071,17.213757,38.770289,260.505721,-427.115091
41,-393.285725,2572.942315,-605.190832,2411.498916,-624.525636,2611.772061,-1010.512372,2325.170593,-1267.472871,2791.948318,211.905107,161.443399,19.334804,-200.273145,256.960498,-466.777725
42,-375.192715,2353.025661,-585.116584,2583.025969,-576.472678,2533.286904,-971.464325,2302.965672,-1287.789350,2699.977404,209.923868,-230.000308,-8.643906,49.739064,316.325025,-397.011732
43,-366.620123,2355.277140,-544.687117,2470.466450,-589.333311,2600.701333,-966.066676,2401.432620,-1251.275658,2711.433453,178.066994,-115.189310,44.646194,-130.234883,285.208982,-310.000833
44,-368.427952,2505.942234,-564.981746,2573.425138,-575.660603,2835.882087,-935.426625,2596.671138,-1313.755339,2555.615528,196.553794,-67.482905,10.678857,-262.456949,378.328714,41.055610
45,-350.901203,2402.913370,-548.960644,2585.609173,-578.460412,2521.193877,-933.644565,2479.598881,-1265.122701,2586.422179,198.059442,-182.695803,29.499768,64.415295,331.478136,-106.823298
46,-355.400848,2678.896040,-553.637210,2459.302175,-606.069385,2767.523294,-984.628314,2435.844932,-1289.129672,2666.325195,198.236362,219.593865,52.432175,-308.221119,304.501359,-230.480263
47,-362.518266,2463.715779,-529.805167,2410.417454,-560.261902,2677.015264,-959.539280,2466.906842,-1286.555844,2745.956290,167.286901,53.298325,30.456735,-266.597810,327.016564,-279.049448
48,-254.287426,2522.952903,-476.506901,2568.520526,-535.455572,2603.756895,-913.343563,2423.504904,-1187.313866,2538.758638,222.219475,-45.567622,58.948671,-35.236370,273.970303,-115.253734
49,-253.914553,2529.643198,-453.641792,2574.518941,-502.153875,2588.215178,-915.890693,2536.066063,-1277.957624,2678.737721,199.727239,-44.875742,48.512084,-13.696237,362.066931,-142.671659