In [1]:
import pandas as pd

In [2]:
import numpy as np

In [130]:
df1=pd.DataFrame()
df1=pd.read_excel('../data/1.xlsx')
df1=df1.dropna()

In [131]:
df1

,timestamp,head_x,head_y,head_z,torso_x,torso_y,torso_z,waist_x,waist_y,waist_z,...,r_hip_z,r_knee_x,r_knee_y,r_knee_z,l_ankle_x,l_ankle_y,l_ankle_z,r_ankle_x,r_ankle_y,r_ankle_z
0,1743993607,-66.57459,346.6133,2153.312,-53.08918,-76.51717,2227.077,-42.61894,-253.0159,2199.219,...,2200.213,-146.0421,-645.2217,2094.135,139.9366,-954.6445,2234.752,-180.1308,-968.9515,2229.294
1,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
2,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
3,1743993607,-55.37650,341.3134,2148.882,-52.14709,-77.80215,2225.404,-43.16278,-255.7176,2202.311,...,2200.134,-147.0702,-660.8210,2072.728,141.4262,-959.2802,2230.064,-180.6705,-976.3017,2226.266
4,1743993608,-45.28284,330.4109,2149.211,-51.05178,-87.53446,2226.210,-43.04076,-265.1855,2202.331,...,2200.013,-151.5682,-664.8762,2056.333,110.5179,-1002.7690,2058.162,-180.9913,-975.9042,2219.510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,1743993622,-71.18983,360.3356,2118.724,-50.02530,-57.78058,2173.144,-44.92595,-239.8437,2154.254,...,2160.997,-161.4635,-664.4786,2077.935,135.1745,-976.7439,2232.596,-175.5972,-990.8358,2226.992
443,1743993622,-71.18983,360.3356,2118.724,-50.02530,-57.78058,2173.144,-44.92595,-239.8437,2154.254,...,2160.997,-161.4635,-664.4786,2077.935,135.1745,-976.7439,2232.596,-175.5972,-990.8358,2226.992
444,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622
445,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622
446,1743993622,-71.09723,365.8696,2118.778,-50.38910,-49.04067,2167.271,-44.08286,-232.1081,2148.591,...,2155.674,-159.5926,-660.0185,2082.340,134.4717,-975.1656,2235.963,-177.6347,-985.7233,2226.622

In [132]:
df_ant = df1[['l_hip_x','l_hip_y','l_knee_x','l_knee_y','l_ankle_x','l_ankle_y']]

In [133]:
df_ant

      l_hip_x   l_hip_y   l_knee_x  l_knee_y  l_ankle_x  l_ankle_y
0    59.56746 -265.5242   99.13966 -632.0627   139.9366  -954.6445
1    59.73900 -281.9015  101.91260 -646.1818   141.4262  -959.2802
2    59.73900 -281.9015  101.91260 -646.1818   141.4262  -959.2802
3    59.73900 -281.9015  101.91260 -646.1818   141.4262  -959.2802
4    60.36124 -289.7710  104.66220 -650.3589   110.5179 -1002.7690
..        ...       ...        ...       ...        ...        ...
442  51.04284 -281.1733   93.28984 -654.5800   135.1745  -976.7439
443  51.04284 -281.1733   93.28984 -654.5800   135.1745  -976.7439
444  53.36913 -277.3993   92.71281 -653.2104   134.4717  -975.1656
445  53.36913 -277.3993   92.71281 -653.2104   134.4717  -975.1656
446  53.36913 -277.3993   92.71281 -653.2104   134.4717  -975.1656

[447 rows x 6 columns]

In [134]:
pd.set_option('mode.chained_assignment', None)
df_ant['l_tibia_x'] = df1['l_knee_x'] - df1['l_ankle_x']
df_ant['l_tibia_y'] = df1['l_knee_y'] - df1['l_ankle_y']
df_ant['l_femur_x'] = df1['l_hip_x'] - df1['l_knee_x']
df_ant['l_femur_y'] = df1['l_hip_y'] - df1['l_knee_y']

In [135]:
df_ant

,l_hip_x,l_hip_y,l_knee_x,l_knee_y,l_ankle_x,l_ankle_y,l_tibia_x,l_tibia_y,l_femur_x,l_femur_y
0,59.56746,-265.5242,99.13966,-632.0627,139.9366,-954.6445,-40.79694,322.5818,-39.57220,366.5385
1,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802,-39.51360,313.0984,-42.17360,364.2803
2,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802,-39.51360,313.0984,-42.17360,364.2803
3,59.73900,-281.9015,101.91260,-646.1818,141.4262,-959.2802,-39.51360,313.0984,-42.17360,364.2803
4,60.36124,-289.7710,104.66220,-650.3589,110.5179,-1002.7690,-5.85570,352.4101,-44.30096,360.5879
...,...,...,...,...,...,...,...,...,...,...
442,51.04284,-281.1733,93.28984,-654.5800,135.1745,-976.7439,-41.88466,322.1639,-42.24700,373.4067
443,51.04284,-281.1733,93.28984,-654.5800,135.1745,-976.7439,-41.88466,322.1639,-42.24700,373.4067
444,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656,-41.75889,321.9552,-39.34368,375.8111
445,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656,-41.75889,321.9552,-39.34368,375.8111
446,53.36913,-277.3993,92.71281,-653.2104,134.4717,-975.1656,-41.75889,321.9552,-39.34368,375.8111

In [136]:
def angle_v2(vec1, vec2):
    # from google
    #import math
    import numpy as np

    np.array 
    
    # 각 벡터의 각도 계산 (x축 기준)
    angle1 = np.arctan2(vec1[:,1], vec1[:,0])
    angle2 = np.arctan2(vec2[:,1], vec2[:,0])

    # 두 각도의 차이 계산
    angle_diff_rad = angle2 - angle1

    # 절대값 및 360도 조정 (필요에 따라)
    angle_diff_deg = np.degrees(angle_diff_rad)
    #angle_diff_deg = np.where( angle_diff_deg < 0, angle_diff_deg + 360, angle_diff_deg )

    return angle_diff_deg

In [137]:
angle_v2(df_ant[['l_tibia_x','l_tibia_y']].values,       df_ant[['l_femur_x','l_femur_y']].values     )[0:50]

array([-1.04603804, -0.58893883, -0.58893883, -0.58893883,  6.05217421,
        6.05217421,  6.05217421,  7.00831698,  7.00831698,  7.00831698,
        7.00831698,  3.63826577,  5.04013666,  5.59643378,  4.93305672,
        5.04789869,  5.45474378,  6.47240246,  6.65108094,  6.65108094,
        6.65108094,  6.65108094,  5.73144701,  5.73144701,  5.73144701,
        4.13124741,  4.13124741,  4.13124741,  3.28872779,  3.28872779,
        3.00636015,  3.00636015,  3.00636015,  2.59694864,  2.59694864,
        2.59694864,  0.34142134,  0.34142134,  0.34142134, -1.85475768,
       -1.85475768, -3.55181251, -2.89652082, -2.43232733, -2.67288565,
       -3.81630449, -3.77114997, -2.64969975, -2.64969975, -2.64969975])

In [138]:
#lateral view
df_lat = df1[['torso_y', 'torso_z', 'waist_y','waist_z','l_hip_y','l_hip_z','l_knee_y','l_knee_z','l_ankle_y','l_ankle_z']]

In [139]:
df_lat['tor_wai_y'] = df_lat['torso_y'] - df_lat['waist_y']
df_lat['tor_wai_z'] = df_lat['torso_z'] - df_lat['waist_z']
df_lat['l_hip_wai_y'] = df_lat['waist_y'] - df_lat['l_hip_y']
df_lat['l_hip_wai_z'] = df_lat['waist_z'] - df_lat['l_hip_z']
df_lat['l_tibia_y'] = df_lat['l_knee_y'] - df_lat['l_ankle_y']
df_lat['l_tibia_z'] = df_lat['l_knee_z'] - df_lat['l_ankle_z']

In [140]:
#low back arch
angle_v2(df_lat[['tor_wai_y', 'tor_wai_z']].values, df_lat[['l_hip_wai_y','l_hip_wai_z']].values)[1:50]

array([-19.52826228, -19.52826228, -19.52826228, -20.47174008,
       -20.47174008, -20.47174008, -23.73355201, -23.73355201,
       -23.73355201, -23.73355201, -40.25215899, -36.58546662,
       -33.60983192, -49.37144954, -53.70712933, -46.33269846,
       -47.13091661, -52.8805865 , -52.8805865 , -52.8805865 ,
       -52.8805865 , -58.33710421, -58.33710421, -58.33710421,
       -35.0178035 , -35.0178035 , -35.0178035 , -16.99112836,
       -16.99112836, -14.70892681, -14.70892681, -14.70892681,
       -17.2000072 , -17.2000072 , -17.2000072 , -20.71642556,
       -20.71642556, -20.71642556, -26.24926783, -26.24926783,
       -26.19067844, -17.44323576, -11.04570688,  -7.11688621,
        -8.87806252, -10.47235255,  -9.91682923,  -9.91682923,
        -9.91682923])

In [141]:
#torso lean forward
angle_v2(df_lat[['l_tibia_y','l_tibia_z']].values, df_lat[['tor_wai_y', 'tor_wai_z']].values)[1:200]

array([34.02183777, 34.02183777, 34.02183777,  7.34679683,  7.34679683,
        7.34679683,  8.39086991,  8.39086991,  8.39086991,  8.39086991,
       39.14362165, 39.85861378, 42.28125645, 44.03910633, 45.81277677,
       47.1871012 , 48.74229991, 49.11906927, 49.11906927, 49.11906927,
       49.11906927, 46.83035541, 46.83035541, 46.83035541, 43.27326755,
       43.27326755, 43.27326755, 42.39249222, 42.39249222, 43.77418098,
       43.77418098, 43.77418098, 44.22042762, 44.22042762, 44.22042762,
       44.62393332, 44.62393332, 44.62393332, 43.88401119, 43.88401119,
       41.89189449, 41.84691539, 41.4524965 , 40.05328272, 38.95191127,
       38.36155005, 38.12047115, 38.12047115, 38.12047115, 38.3280776 ,
       38.3280776 , 38.3280776 , 39.00368171, 39.00368171, 39.00368171,
       37.17787891, 37.17787891, 37.17787891, 37.42534863, 37.42534863,
       37.42534863, 37.42534863, 37.57295551, 37.57295551, 37.57295551,
       36.56585065, 36.56585065, 36.31812527, 36.31812527, 36.31812527,
       37.27096604, 37.03545113, 36.27050436, 34.58098333, 34.68744851,
       35.20283142, 35.38520684, 35.38520684, 35.38520684, 34.21091777,
       34.21091777, 34.21091777, 32.87384139, 32.87384139, 32.87384139,
       29.78473639, 29.78473639, 29.78473639, 29.78473639, 27.11489424,
       27.11489424, 27.11489424, 26.10453241, 26.10453241, 25.81190828,
       25.81190828, 25.81190828, 27.88960002, 27.88960002, 27.88960002,
       28.41941031, 25.98737134, 23.12632435, 22.28586208, 22.07861087,
       21.23237675, 21.23237675, 21.23237675, 21.23237675, 19.770484  ,
       19.770484  , 19.770484  , 19.36723687, 19.36723687, 19.79469898,
       19.79469898, 19.79469898, 19.79469898, 21.71814724, 21.71814724,
       21.71814724, 21.90424549, 21.90424549, 24.44182368, 24.44182368,
       24.44182368, 24.44182368, 29.26165443, 29.26165443, 29.26165443,
       32.25326109, 34.91465012, 36.57245113, 37.64864386, 38.30758236,
       37.86324116, 38.94175734, 38.94175734, 38.94175734, 38.81142679,
       38.81142679, 38.81142679, 41.21935361, 41.21935361, 41.21935361,
       42.51717596, 42.51717596, 42.51717596, 41.95573349, 41.95573349,
       39.91616283, 39.91616283, 39.91616283, 39.26955915, 39.26955915,
       39.26955915, 33.54654671, 33.54654671, 33.54654671, 36.51057912,
       36.51057912, 39.52656373, 41.0096155 , 39.97503631, 38.9030854 ,
       36.91063349, 34.33882806, 31.39750339, 31.39750339, 31.39750339,
       31.39750339, 28.86659698, 28.86659698, 28.86659698, 28.86659698,
       28.1543118 , 28.1543118 , 28.1543118 , 28.1543118 , 25.29661761,
       25.29661761, 25.29661761, 22.84068565, 22.84068565, 22.84068565,
       22.85513381, 22.85513381, 22.85513381, 24.01566133, 24.80281632,
       24.98702381, 24.46607374, 24.24788557, 24.34067526, 24.45508372,
       24.45508372, 24.45508372, 24.76644269, 24.76644269])

In [142]:
df_lat[30:70]

,torso_y,torso_z,waist_y,waist_z,l_hip_y,l_hip_z,l_knee_y,l_knee_z,l_ankle_y,l_ankle_z,tor_wai_y,tor_wai_z,l_hip_wai_y,l_hip_wai_z,l_tibia_y,l_tibia_z
30,-221.1831,2239.191,-398.5157,2230.671,-430.2256,2237.387,-746.2056,1994.084,-1025.701,2237.247,177.3326,8.520,31.7099,-6.716,279.4954,-243.163
31,-221.1831,2239.191,-398.5157,2230.671,-430.2256,2237.387,-746.2056,1994.084,-1025.701,2237.247,177.3326,8.520,31.7099,-6.716,279.4954,-243.163
32,-221.1831,2239.191,-398.5157,2230.671,-430.2256,2237.387,-746.2056,1994.084,-1025.701,2237.247,177.3326,8.520,31.7099,-6.716,279.4954,-243.163
33,-231.8995,2241.046,-408.4230,2231.109,-439.5533,2238.858,-750.6522,1993.069,-1033.651,2239.063,176.5235,9.937,31.1303,-7.749,282.9988,-245.994
34,-231.8995,2241.046,-408.4230,2231.109,-439.5533,2238.858,-750.6522,1993.069,-1033.651,2239.063,176.5235,9.937,31.1303,-7.749,282.9988,-245.994
35,-231.8995,2241.046,-408.4230,2231.109,-439.5533,2238.858,-750.6522,1993.069,-1033.651,2239.063,176.5235,9.937,31.1303,-7.749,282.9988,-245.994
36,-250.3996,2242.472,-426.4955,2231.999,-459.7153,2242.354,-758.7940,1991.497,-1042.533,2240.070,176.0959,10.473,33.2198,-10.355,283.7390,-248.573
37,-250.3996,2242.472,-426.4955,2231.999,-459.7153,2242.354,-758.7940,1991.497,-1042.533,2240.070,176.0959,10.473,33.2198,-10.355,283.7390,-248.573
38,-250.3996,2242.472,-426.4955,2231.999,-459.7153,2242.354,-758.7940,1991.497,-1042.533,2240.070,176.0959,10.473,33.2198,-10.355,283.7390,-248.573
39,-262.8572,2243.490,-437.7896,2232.693,-468.7188,2245.642,-760.0178,1991.223,-1046.820,2234.898,174.9324,10.797,30.9292,-12.949,286.8022,-243.675
40,-262.8572,2243.490,-437.7896,2232.693,-468.7188,2245.642,-760.0178,1991.223,-1046.820,2234.898,174.9324,10.797,30.9292,-12.949,286.8022,-243.675
41,-271.0562,2248.734,-444.3210,2236.419,-480.0812,2250.958,-763.0983,1990.453,-1055.534,2217.505,173.2648,12.315,35.7602,-14.539,292.4357,-227.052
42,-274.6661,2259.042,-446.5440,2245.943,-485.3638,2254.966,-766.1923,1990.779,-1055.206,2212.457,171.8779,13.099,38.8198,-9.023,289.0137,-221.678
43,-279.8775,2263.676,-451.2158,2253.445,-493.1765,2259.065,-771.5778,1994.465,-1053.994,2215.393,171.3383,10.231,41.9607,-5.620,282.4162,-220.928
44,-287.3624,2264.928,-458.3603,2260.546,-501.6406,2264.827,-774.7867,1998.416,-1051.888,2219.507,170.9979,4.382,43.2803,-4.281,277.1013,-221.091
45,-294.6537,2268.546,-464.0021,2265.265,-501.7688,2270.417,-770.3267,2002.077,-1047.913,2217.721,169.3484,3.281,37.7667,-5.152,277.5863,-215.644
46,-294.7265,2274.732,-462.7485,2268.813,-501.6803,2274.600,-766.8483,2005.150,-1048.651,2212.488,168.0220,5.919,38.9318,-5.787,281.8027,-207.338
47,-289.9237,2278.401,-459.2908,2272.628,-501.1102,2278.479,-764.4971,2008.893,-1046.664,2215.168,169.3671,5.773,41.8194,-5.851,282.1669,-206.275
48,-289.9237,2278.401,-459.2908,2272.628,-501.1102,2278.479,-764.4971,2008.893,-1046.664,2215.168,169.3671,5.773,41.8194,-5.851,282.1669,-206.275
49,-289.9237,2278.401,-459.2908,2272.628,-501.1102,2278.479,-764.4971,2008.893,-1046.664,2215.168,169.3671,5.773,41.8194,-5.851,282.1669,-206.275
50,-282.1044,2280.574,-453.5078,2275.863,-498.4439,2279.466,-764.0583,2015.010,-1043.951,2224.044,171.4034,4.711,44.9361,-3.603,279.8927,-209.034
51,-282.1044,2280.574,-453.5078,2275.863,-498.4439,2279.466,-764.0583,2015.010,-1043.951,2224.044,171.4034,4.711,44.9361,-3.603,279.8927,-209.034
52,-282.1044,2280.574,-453.5078,2275.863,-498.4439,2279.466,-764.0583,2015.010,-1043.951,2224.044,171.4034,4.711,44.9361,-3.603,279.8927,-209.034
53,-271.5815,2278.812,-442.4715,2277.328,-490.6354,2279.646,-763.7992,2023.793,-1037.624,2241.651,170.8900,1.484,48.1639,-2.318,273.8248,-217.858
54,-271.5815,2278.812,-442.4715,2277.328,-490.6354,2279.646,-763.7992,2023.793,-1037.624,2241.651,170.8900,1.484,48.1639,-2.318,273.8248,-217.858
55,-271.5815,2278.812,-442.4715,2277.328,-490.6354,2279.646,-763.7992,2023.793,-1037.624,2241.651,170.8900,1.484,48.1639,-2.318,273.8248,-217.858
56,-258.1984,2276.272,-432.6815,2277.530,-471.6274,2280.019,-755.9952,2028.628,-1035.841,2244.068,174.4831,-1.258,38.9459,-2.489,279.8458,-215.440
57,-258.1984,2276.272,-432.6815,2277.530,-471.6274,2280.019,-755.9952,2028.628,-1035.841,2244.068,174.4831,-1.258,38.9459,-2.489,279.8458,-215.440
58,-258.1984,2276.272,-432.6815,2277.530,-471.6274,2280.019,-755.9952,2028.628,-1035.841,2244.068,174.4831,-1.258,38.9459,-2.489,279.8458,-215.440
59,-248.4523,2277.071,-420.2423,2276.708,-465.5927,2279.984,-749.2421,2023.326,-1033.160,2239.647,171.7900,0.363,45.3504,-3.276,283.9179,-216.321
60,-248.4523,2277.071,-420.2423,2276.708,-465.5927,2279.984,-749.2421,2023.326,-1033.160,2239.647,171.7900,0.363,45.3504,-3.276,283.9179,-216.321
61,-248.4523,2277.071,-420.2423,2276.708,-465.5927,2279.984,-749.2421,2023.326,-1033.160,2239.647,171.7900,0.363,45.3504,-3.276,283.9179,-216.321
62,-248.4523,2277.071,-420.2423,2276.708,-465.5927,2279.984,-749.2421,2023.326,-1033.160,2239.647,171.7900,0.363,45.3504,-3.276,283.9179,-216.321
63,-236.6005,2276.481,-408.2159,2275.440,-462.6026,2279.573,-739.7280,2016.725,-1033.115,2239.623,171.6154,1.041,54.3867,-4.133,293.3870,-222.898
64,-236.6005,2276.481,-408.2159,2275.440,-462.6026,2279.573,-739.7280,2016.725,-1033.115,2239.623,171.6154,1.041,54.3867,-4.133,293.3870,-222.898
65,-236.6005,2276.481,-408.2159,2275.440,-462.6026,2279.573,-739.7280,2016.725,-1033.115,2239.623,171.6154,1.041,54.3867,-4.133,293.3870,-222.898
66,-228.0143,2276.551,-399.5680,2274.584,-452.1607,2278.985,-733.3717,2021.378,-1035.838,2240.399,171.5537,1.967,52.5927,-4.401,302.4663,-219.021
67,-228.0143,2276.551,-399.5680,2274.584,-452.1607,2278.985,-733.3717,2021.378,-1035.838,2240.399,171.5537,1.967,52.5927,-4.401,302.4663,-219.021
68,-217.0495,2279.037,-388.3121,2273.634,-431.5731,2278.348,-724.8460,2026.839,-1035.278,2240.282,171.2626,5.403,43.2610,-4.714,310.4320,-213.443
69,-217.0495,2279.037,-388.3121,2273.634,-431.5731,2278.348,-724.8460,2026.839,-1035.278,2240.282,171.2626,5.403,43.2610,-4.714,310.4320,-213.443

In [143]:
from scipy.signal import argrelextrema
import scipy

In [144]:
x = df_lat['torso_y'].rolling(window=25).mean().values
# Find indices of local maxima using np.greater as the comparator
maxima_indices = argrelextrema(x, np.less)

print("Data array:", x)
print("Indices of local maxima:", maxima_indices)
# Output: Indices of local maxima: (array([3, 6]),)

Data array: [         nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan          nan
          nan          nan          nan          nan -139.350432
 -144.6214892 -149.8411472 -155.0608052 -160.3599192 -165.2697408
 -170.6156864 -175.961632  -180.747788  -185.9626    -191.177412
 -196.392224  -201.421904  -206.149564  -210.17032   -214.186156
 -217.882796  -221.599008  -225.093216  -228.482644  -232.171468
 -236.151944  -240.135332  -243.473092  -246.810852  -250.148612
 -253.101044  -256.053476  -259.005908  -261.457968  -263.910028
 -265.925964  -267.406576  -268.887188  -269.939144  -270.601256
 -271.263368  -271.185476  -271.107584  -270.55562   -269.505352
 -268.455084  -266.733408  -264.867336  -262.354216  -259.5417
 -256.437532  -252.96372   -249.148484  -244.833312  -240.160968
 -235.43444   -230.16296   -224.226404  -218.710764  -213.195124
 -206.937284  -201.214768  -195.492252  -188.5761628 -182.0499176
 -175.5236724 -168.530902  -161.5381316 -155.0194332 -148.5007348
 -141.62116   -135.0850332 -128.5489064 -122.2364532 -115.924
 -109.5753464 -103.5934248  -98.1450392  -93.2941484  -88.8004296
  -84.6736668  -81.1606072  -78.4306848  -75.7978696  -73.2086056
  -71.3807812  -69.5618228  -67.7428644  -67.1174792  -66.492094
  -65.9115596  -65.7975504  -65.6835412  -65.2826216  -64.881702
  -64.6033404  -64.3249788  -64.0466172  -63.983174   -63.6561536
  -63.3653336  -63.0745136  -62.6855     -62.1989276  -61.6640428
  -61.129158   -60.525522   -59.8038248  -59.4918076  -59.1362392
  -58.7614312  -58.8164836  -59.511116   -60.8004824  -62.7243688
  -65.1359604  -68.06894    -71.7183196  -75.6546096  -79.5908996
  -84.568924   -89.5469484  -94.5249728 -100.1389772 -106.0165588
 -111.8941404 -118.207998  -124.6200492 -131.0321004 -138.02948
 -145.0268596 -152.5328432 -160.0388268 -167.0380232 -174.3780516
 -181.71808   -188.619382  -195.368352  -201.522588  -207.042304
 -212.157284  -216.750876  -220.753832  -224.739192  -228.369196
 -230.071132  -230.717908  -230.303844  -227.641616  -224.979388
 -222.31716   -219.218656  -214.6593492 -210.1000424 -205.0037196
 -199.9073968 -193.2222688 -186.5371408 -179.8520128 -172.8260528
 -165.220378  -157.6147032 -149.5217804 -141.5312692 -133.540758
 -125.4224268 -117.3907892 -109.2333876 -101.093582   -93.4242384
  -86.8415176  -81.1765436  -76.4842764  -73.5238352  -70.7626224
  -68.1140912  -65.46556    -64.2778316  -63.1585052  -62.0391788
  -60.9198524  -60.9225224  -60.9251924  -60.9278624  -60.9305324
  -61.5360948  -62.1416572  -62.7472196  -63.2528284  -63.7584372
  -64.264046   -64.6935316  -65.1230172  -65.5647336  -65.891344
  -66.2559836  -66.9747484  -67.7816464  -68.4689024  -69.3187464
  -70.0559088  -70.7930712  -71.9869408  -73.657898   -76.0369872
  -79.3993084  -83.4636904  -88.0953564  -92.7270224  -97.3586884
 -102.2816808 -107.2046732 -112.1276656 -117.419284  -122.7109024
 -128.0025208 -134.2564288 -140.5103368 -146.752014  -153.7562752
 -160.7605364 -167.5480856 -174.8186508 -182.089216  -188.9979648
 -196.1065776 -203.2151904 -210.083332  -216.405984  -222.020504
 -226.692744  -230.621128  -233.782244  -236.405232  -238.377676
 -238.795564  -238.168804  -236.705064  -234.084892  -231.46472
 -228.844548  -223.8020024 -218.7594568 -213.7169112 -207.9117816
 -201.2339048 -194.556028  -186.9350264 -179.3140248 -171.6930232
 -163.6546256 -155.616228  -147.3615944 -139.1069608 -130.9333688
 -122.7188248 -114.4638508 -106.4088608  -98.8919988  -91.8252116
  -85.9984764  -81.1878924  -77.1747624  -73.921502   -70.6577888
  -67.383684   -65.5457132  -63.6781892  -61.8106652  -59.9431412
  -58.948512   -57.9538828  -57.4193624  -56.8809528  -56.3425432
  -56.0216656  -55.4534608  -54.885256   -54.3170512  -53.5802576
  -52.843464   -52.5148556  -52.1862472  -51.8576388  -52.373812
  -52.8899852  -53.4346552  -54.4152388  -55.4213008  -57.456378
  -59.5018468  -61.5606952  -64.6204368  -68.7377384  -73.784296
  -79.788662   -86.786888   -94.742962  -103.5289812 -112.3150004
 -121.1010196 -130.658498  -140.2159764 -149.7734548 -159.4184804
 -169.702798  -179.6193604 -189.5359228 -199.6572372 -209.1342392
 -218.7553012 -228.3763632 -237.6010376 -246.774992  -254.930384
 -263.085776  -271.14316   -278.229204  -284.257688  -289.041904
 -292.868164  -295.05422   -295.4962    -294.252916  -292.017852
 -288.664484  -283.723248  -277.848912  -271.974576  -266.10024
 -258.772716  -251.445192  -244.117668  -235.6407368 -227.1638056
 -218.5428144 -209.1240956 -199.7053768 -189.8305536 -179.9557304
 -170.0809072 -160.0465356 -150.012164  -139.9777924 -130.2470288
 -120.5162652 -111.4318456 -103.227022   -95.8814064  -89.6285852
  -84.494068   -80.4232868  -77.3755664  -74.381096   -71.4310308
  -69.3331468  -67.2723292  -65.2451572  -64.1886496  -63.132142
  -62.0756344  -61.8347516  -61.5938688  -61.8598104  -62.125752
  -62.3161472  -62.7640988  -63.2120504  -63.4827068  -63.7647672
  -64.0468276  -64.760998   -65.3818004  -66.0026028  -67.520404
  -69.0382052  -70.5560064  -74.0466908  -77.4841252  -80.8771544
  -85.5210304  -90.9021     -96.964328  -103.6297348 -110.6433096
 -118.3826004 -126.568722  -135.0778636 -143.8917252 -152.7055868
 -161.5949948 -170.6163988 -179.6378028 -188.836502  -198.0699852
 -207.3034684 -216.1048416 -224.8829388 -233.661036  -241.44112
 -248.999668  -256.558216  -261.300476  -266.042736  -270.784996
 -273.493568  -275.42788   -276.647388  -276.436996  -275.878436
 -274.59416   -272.031296  -268.250144  -263.086612  -257.039076
 -250.672216  -243.358856  -235.0663348 -226.1015748 -217.1020308
 -208.1024868 -198.698586  -189.3179612 -179.9373364 -170.2071152
 -160.69843   -151.1897448]
Indices of local maxima: (array([ 60, 166, 255, 342, 427]),)

In [84]:
peaks, _ = scipy.signal.find_peaks(x)
#출처: https://super-master.tistory.com/90 [MJ Career Orchestration:티스토리]

In [52]:
peaks

array([  4,   9,  12,  18,  23,  25,  30,  34,  36,  43,  45,  64,  66,
        68,  70,  73,  75,  78,  89,  92,  95,  97,  99, 104, 106, 120,
       124, 127, 132, 135, 139, 153, 156, 159, 162, 165, 178, 189, 191,
       194, 198, 210, 212, 215, 218, 222, 227, 231, 242, 245, 247, 251,
       256, 258, 261, 275, 279, 281, 286, 288])